- model: batch.facility
  pk: 1
  fields:
    name: MyBinder
    description: MyBinder
    url: https://mybinder.org/
    facilitytype: jupyterhub
    runtimeengine: Docker
- model: batch.facility
  pk: 2
  fields:
    name: Rosetta @ INAF OATS
    description: The Rosetta platform deployed at INAF OATS computing centre
    url:  https://esap-rosetta.oats.inaf.it/
    facilitytype: jupyterhub
    runtimeengine: Singularity
- model: batch.workflow
  pk: 1
  fields:
    name: CSIC-IAA HCG-16 workflow
    description: Analysis of Hickson Compact Group 16
    url: https://github.com/AMIGA-IAA/hcg-16
    ref: HEAD
    workflowtype: notebook
- model: batch.workflow
  pk: 2
  fields:
    name: CDS MOCPy
    description: Experiment with Multi-Order Coverage maps
    url: https://github.com/cds-astro/mocpy
    ref: HEAD
    workflowtype: notebook
