- model: ida.facility
  pk: 1
  fields:
    name: MyBinder
    description: MyBinder
    url: https://mybinder.org/
    facilitytype: jupyterhub
- model: ida.facility
  pk: 2
  fields:
    name: RenkuLab
    description: RenkuLab
    url:  https://renkulab.io/
    facilitytype: jupyterhub
- model: ida.facility
  pk: 3
  fields:
    name: JIVE BinderHub
    description: JIVE BinderHub
    url:  http://jupyter.jive.nl/binderhub/
    facilitytype: jupyterhub
- model: ida.facility
  pk: 4
  fields:
    name: SKAO BinderHub
    description: SKAO BinderHub
    url:  https://srcdev.skatelescope.org/binderhub/
    facilitytype: jupyterhub

- model: ida.workflow
  pk: 1
  fields:
    name: CTA Gammapy Example
    description: CTA Gammapy Example
    url: https://git.astron.nl/astron-sdc/escape-wp5/workflows/cta-example
    ref: master
    filepath: gammapy-tutorials/notebooks-0.18.2/cta.ipynb
    workflowtype: notebook
    keywords: jupyter-notebook
    author: 
    runtimePlatform: Python

- model: ida.workflow
  pk: 2
  fields:
    name: HESS DR3 analysis with gammapy
    description: HESS DR3 analysis with gammapy
    url: https://renkulab.io/gitlab/vladimir.savchenko/hess
    #url: https://renkulab.io/gitlab/andrii.neronov/hess/-/tree/b301e20116a5d922ed2d5cc0a23d90b05892e4e4
    ref: master
    filepath: Untitled.ipynb
    workflowtype: notebook
    keywords: jupyter-notebook
    author: 
    runtimePlatform: Python


- model: ida.workflow
  pk: 6
  fields:
    name: TOPCAT
    description: TOPCAT is an interactive graphical viewer and editor for tabular data
    url: http://www.star.bris.ac.uk/~mbt/topcat/
    ref: master
    filepath:
    workflowtype: desktop
    keywords: desktop
    author: Mark Taylor
    runtimePlatform: Java

