- model: ida.facility
  fields:
    id: 1
    name: MyBinder
    description: MyBinder
    url: https://mybinder.org/
    facilitytype: jupyterhub
- model: ida.workflow
  fields:
    id: 1
    name: CSIC-IAA HCG-16 workflow
    description: Analysis of Hickson Compact Group 16
    url: https://github.com/AMIGA-IAA/hcg-16
    ref: HEAD,
    filepath:
    workflowtype: notebook
- model: ida.workflow
  fields:
    id: 2
    name: CDS MOCPy
    description: Experiment with Multi-Order Coverage maps
    url: https://github.com/cds-astro/mocpy/master
    ref: HEAD,
    filepath:
    workflowtype: notebook
- model: ida.workflow
  fields:
    id: 3
    name: ASTRON VO Apertif
    description: ASTRON VO Apertif
    url: https://git.astron.nl/astron-sdc/escape-wp5/workflows/apertif-vo-example
    ref: HEAD,
    filepath: PyVO.ipynb
    workflowtype: notebook
- model: ida.workflow
  fields:
    id: 5
    name: Apertif  Visualization
    description: Shopping Basket and Apertif Visualization Example
    url: https://git.astron.nl/astron-sdc/escape-wp5/workflows/apertif-vis-example
    ref: HEAD,
    filepath: ApertifVisualization.ipynb
    workflowtype: notebook
- model: ida.workflow
  fields:
    id: 6
    name: Zooniverse Muon Hunters
    description: Shopping Cart and Zooniverse Example
    url: https://git.astron.nl/astron-sdc/escape-wp5/workflows/muon-hunters-example
    ref: HEAD,
    filepath: ProcessMuonHunterData.ipynb
    workflowtype: notebook