version: '3.4'

networks:
  esap_network: 
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  esap_api:
    container_name: esap_api
    image: git.astron.nl:5000/astron-sdc/esap-api-gateway
    expose:
      - 8000
    networks:
      - traefik_proxy
      - esap_network
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.esap-api.entryPoints=websecure"
      - "traefik.http.routers.esap-api.service=esap-api"
      - "traefik.http.routers.esap-api.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/esap-api`)"
      - "traefik.http.services.esap-api.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.esap-api.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.esap-api.headers.customrequestheaders.Access-Control-Allow-Origin=*"
      - "traefik.http.middlewares.esap-api.headers.customrequestheaders.Access-Control-Max-Age=3600"

      - "traefik.http.routers.esap-static_esap.entryPoints=websecure"
      - "traefik.http.routers.esap-static_esap.service=esap-static_esap"
      - "traefik.http.routers.esap-static_esap.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/static_esap`)"
      - "traefik.http.services.esap-static_esap.loadbalancer.server.port=8000"

      # route to the '/oidc' authentication
      - "traefik.http.routers.esap-oidc.entryPoints=websecure"
      - "traefik.http.routers.esap-oidc.service=esap-oidc"
      - "traefik.http.routers.esap-oidc.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/oidc`)"
      - "traefik.http.services.esap-oidc.loadbalancer.server.port=8000"

    env_file:
      - $HOME/shared/oidc.env
      - $HOME/shared/esap.env
    restart: always
    volumes:
      - $HOME/shared/esap-gateway-query/:/shared


  # this is an extra instance of esap-api on port 5555
  esap_api_5555:
    container_name: esap_api_5555
    image: git.astron.nl:5000/astron-sdc/esap-api-gateway
    expose:
      - 8000
    networks:
      - traefik_proxy
      - esap_network
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.esap-api-5555.entryPoints=esap-api-query"
      - "traefik.http.routers.esap-api-5555.service=esap-api-5555"
      - "traefik.http.routers.esap-api-5555.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/esap-api`)"
      - "traefik.http.services.esap-api-5555.loadbalancer.server.port=8000"

      - "traefik.http.services.esap-static-5555.loadbalancer.server.port=8000"
      - "traefik.http.routers.esap-static-5555.entryPoints=esap-api-query"
      - "traefik.http.routers.esap-static-5555.service=esap-static-5555"
      - "traefik.http.routers.esap-static-5555.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/static_esap`)"

      # route to the '/oidc' authentication
      - "traefik.http.routers.esap-oidc.entryPoints=websecure"
      - "traefik.http.routers.esap-oidc.service=esap-oidc"
      - "traefik.http.routers.esap-oidc.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/oidc`)"
      - "traefik.http.services.esap-oidc.loadbalancer.server.port=8000"

    env_file:
      - $HOME/shared/oidc.env
      - $HOME/shared/esap.env
    restart: always
    volumes:
      - $HOME/shared/esap-gateway-query/:/shared

# uncomment the following section if the esap-gui frontend has to run in a container.
# in that case, also adjust the /static/ proxy section in the esap_nginx.conf file
#  esap_gui:
#    build:
#        context: $HOME/my_docker/esap-gui
#        dockerfile: Dockerfile
#    container_name: esap-gui-compose
#    ports:
#      - "8017:80"
#    expose:
#      - "8017"
#    networks:
#      - esap_network
#    restart: always


  esap_nginx:
    build:
        context: $HOME/shared
        dockerfile: Dockerfile
    container_name: esap_nginx
    image: esap_nginx:latest
    networks:
      - traefik_proxy
      - esap_network
    labels:
      - "traefik.enable=true"

      # route to esap-gui
      - "traefik.http.routers.esap-gui.entryPoints=websecure"
      - "traefik.http.routers.esap-gui.service=esap-gui"
      - "traefik.http.routers.esap-gui.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/esap-gui`)"
      - "traefik.http.services.esap-gui.loadbalancer.server.port=80"

      # route to adex-gui
      - "traefik.http.routers.adex-gui.entryPoints=websecure"
      - "traefik.http.routers.adex-gui.service=adex-gui"
      - "traefik.http.routers.adex-gui.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/adex-gui`)"
      - "traefik.http.services.adex-gui.loadbalancer.server.port=80"

      # route to astron-hips
      - "traefik.http.routers.astron-hips.entryPoints=websecure"
      - "traefik.http.routers.astron-hips.service=astron-hips"
      - "traefik.http.routers.astron-hips.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/astron-hips`)"
      - "traefik.http.services.astron-hips.loadbalancer.server.port=80"

      # route to react-aladin (demo project)
      - "traefik.http.routers.react-aladin.entryPoints=websecure"
      - "traefik.http.routers.react-aladin.service=react-aladin"
      - "traefik.http.routers.react-aladin.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/react-aladin`)"
      - "traefik.http.services.react-aladin.loadbalancer.server.port=80"

      # route to exoplanets (demo project)
      - "traefik.http.routers.exoplanets.entryPoints=websecure"
      - "traefik.http.routers.exoplanets.service=exoplanets"
      - "traefik.http.routers.exoplanets.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/exoplanets`)"
      - "traefik.http.services.exoplanets.loadbalancer.server.port=80"

      # route the '/static' calls for the esap-gui frontend
      - "traefik.http.routers.esap-static.entryPoints=websecure"
      - "traefik.http.routers.esap-static.service=esap-static"
      - "traefik.http.routers.esap-static.rule=Host(`sdc-dev.astron.nl`) && PathPrefix(`/static`)"
      - "traefik.http.services.esap-static.loadbalancer.server.port=80"


    volumes:
      - $HOME/shared:/shared
      - $HOME/shared:/etc/nginx/conf.d
      - $HOME/shared/static:/static
    restart: always

