apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esap.fullname" . }}
  labels:
    {{- include "esap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "esap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "esap.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: esap-nginx-volume
        configMap:
          name: esap-nginx
      - name: esap-nginx-htpasswd
        secret:
          secretName: esap-nginx-htpasswd
      - name: esap-api-settings
        configMap:
          name: esap-api-settings
      {{- if .Values.composer.enabled }}
      - name: esap-autogen-repositories
        persistentVolumeClaim:
          claimName: pvc-esap-autogen-repositories
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "esap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageGUI.repository }}:{{ .Values.imageGUI.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageGUI.pullPolicy }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: / #health
              port: http
          readinessProbe:
            httpGet:
              path: / #health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: API_HOST
            value: "https://{{ (index .Values.ingress.hosts 0).host }}/esap-api"
          - name: NODE_ENV
            value: "development"
          - name: RUCIO_HOST
            value: https://rucio.test-cta-cscs.odahub.io/
          - name: RUCIO_AUTH_HOST
            value: https://rucio-auth.test-cta-cscs.odahub.io/
          {{- range $key, $value := .Values.oidc }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: esap-nginx-volume
            mountPath: /etc/nginx/conf.d/default.conf
            # mountPath: /etc/nginx/conf.d/nginx.conf
            subPath: nginx.conf
            readOnly: true
            #- name: esap-nginx-htpasswd
            #mountPath: /etc/nginx/htpasswd
            #subPath: htpasswd
            #readOnly: true
          {{- if .Values.composer.enabled }}
          - mountPath: "/usr/share/nginx/html/git"
            name: esap-autogen-repositories
            readOnly: true
          {{- end }}

        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageAPI.repository }}:{{ .Values.imageAPI.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageAPI.pullPolicy }}
          command:
          - bash 
          - -c
          - "python manage.py runserver 0.0.0.0:8000 --settings=esap.settings.{{ .Values.esap_api_settings_kind }} -v3"
          ports:
          - name: http
            containerPort: 8000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /esap-api/ida
              port: http
          readinessProbe:
            httpGet:
              path: /esap-api/ida
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: SECRET_KEY
            value: "{{ .Values.django_secret_key }}"
          - name: NODE_ENV
            value: "development"
          - name: RUCIO_HOST
            value: https://rucio.test-cta-cscs.odahub.io/
          - name: RUCIO_AUTH_HOST
            value: https://rucio-auth.test-cta-cscs.odahub.io/
          {{- range $key, $value := .Values.oidc }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: esap-api-settings
            mountPath: /src/esap/settings/prod.py
            subPath: prod.py
            readOnly: true
          - mountPath: "/share/git"
            name: esap-autogen-repositories
            readOnly: false



      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
