apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-esap-autogen-repositories
spec:
  storageClassName: "{{ .Values.storageClass }}"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
