{{- if .Values.composer.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-esap-autogen-repositories
spec:
  storageClassName: "{{ .Values.composer.storageClass }}"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
{{- end -}}