# Generated by Django 4.0.2 on 2022-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=240)),
                ('facilitytype', models.CharField(max_length=240)),
                ('runtimeengine', models.CharField(default='none', max_length=240)),
            ],
            options={
                'ordering': ['facilitytype', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=240)),
                ('ref', models.CharField(default='HEAD', max_length=240)),
                ('filepath', models.CharField(blank=True, max_length=240)),
                ('workflowtype', models.CharField(max_length=240)),
            ],
        ),
    ]
