# Generated by Django 3.1.4 on 2022-04-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=240)),
                ('facilitytype', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=240)),
                ('ref', models.CharField(default='HEAD', max_length=240)),
                ('filepath', models.CharField(blank=True, max_length=240)),
                ('workflowtype', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('dataset', models.PositiveIntegerField()),
                ('datatype', models.CharField(max_length=240)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.facility')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch.workflow')),
            ],
        ),
    ]
