# Generated by Django 2.2.9 on 2019-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('instrument', models.CharField(default='unknown', max_length=30)),
                ('description', models.CharField(default='unknown', max_length=1000)),
            ],
        ),
    ]
