# Generated by Django 2.2.9 on 2019-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.CharField(default='https://alta.astron.nl/alta-static/unknown.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
