# Generated by Django 2.2.9 on 2019-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191230_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='thumbnail',
            field=models.CharField(default='https://alta.astron.nl/alta-static/unknown.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.CharField(default='unknown', max_length=1000),
        ),
    ]
