# Generated by Django 2.2.9 on 2020-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191230_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='url_to_archive',
            field=models.CharField(default='', max_length=200),
        ),
    ]
