# Generated by Django 2.2.9 on 2020-01-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_datasource_url_to_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='datatype',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='datasource',
            name='processing_level',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uri',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
