# Generated by Django 2.2.9 on 2020-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200103_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='thumbnail',
            new_name='thumbnail_primary',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='url_to_archive',
        ),
        migrations.AddField(
            model_name='datasource',
            name='archive_name',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='datasource',
            name='archive_url',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='thumbnail_secondary',
            field=models.CharField(default='https://alta.astron.nl/alta-static/unknown.jpg', max_length=200),
        ),
    ]
