# Generated by Django 2.2.9 on 2020-01-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200103_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='documentation_url',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='datasource',
            name='short_description',
            field=models.CharField(default='unknown', max_length=40),
        ),
    ]
