# Generated by Django 2.2.9 on 2020-01-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200103_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='archive_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='archive_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='datatype',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='documentation_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='instrument',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='processing_level',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='short_description',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='thumbnail_secondary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='uri',
            field=models.CharField(max_length=40),
        ),
    ]
