# Generated by Django 2.2.9 on 2020-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200103_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='archive_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='documentation_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='thumbnail_primary',
            field=models.URLField(default='https://alta.astron.nl/alta-static/unknown.jpg'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='thumbnail_secondary',
            field=models.URLField(),
        ),
    ]
