# Generated by Django 2.2.9 on 2020-01-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200103_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='retrieval_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='scientific_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='documentation_url',
            field=models.URLField(null=True),
        ),
    ]
