version: '3.4'

networks:
  esap_network:
  default:
    driver: bridge

services:

  esap_api:
    build:
      context: $ESAP_ROOT/esap-api-gateway/esap
      dockerfile: Dockerfile
    container_name: esap_api_gateway
    image: esap_api_gateway:latest
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - esap_network
    env_file:
      - $ESAP_SHARED/oidc.env
      - $ESAP_SHARED/esap.env
    restart: always
    volumes:
      - $ESAP_SHARED/:/shared

  esap_gui:
    build:
      context: $ESAP_ROOT/esap-gui
      dockerfile: Dockerfile
    container_name: esap_gui
    image: esap_gui:latest
    networks:
      - esap_network
    ports:
      - 80:80
    volumes:
      - $ESAP_ROOT/esap-gui:/shared
      - $ESAP_ROOT/esap-gui:/etc/nginx/conf.d
      - $ESAP_ROOT/esap-gui/static:/static
    restart: always
