# Generated by Django 3.0.2 on 2020-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='archive',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='equinox',
            field=models.CharField(blank=True, choices=[('J2000', 'J2000'), ('ICRS', 'ICRS'), ('N/A', 'N/A')], default='ICRS', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='collection',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='esapbaseobject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='esapbaseobject',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
