# Generated by Django 3.1.4 on 2021-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='ref',
            field=models.CharField(default='HEAD', max_length=240),
        ),
    ]
