# Generated by Django 3.1.4 on 2021-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida', '0002_workflow_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='filepath',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
