# Generated by Django 4.0.3 on 2022-05-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ida', '0003_workflow_filepath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['facilitytype', 'name']},
        ),
    ]
