services:
  rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
      - "5672:5672"
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "uws_jobs"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
