version: '3.4'

networks:
  esap_network: 
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  esap_api_query:
    container_name: esap_api_master
    image: esap_api_master:latest
    ports:
      - 15671:8000
    expose:
      - 8000
    networks:
      - esap_network
    env_file:
      - $HOME/shared/oidc.env
    restart: always
    volumes:
      - $HOME/shared/esap-gateway-master/:/shared


