version: '3.4'

networks:
  esap_network: 
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  esap_api:
    container_name: esap_api_query
    image: esap_api_query:latest
#    ports:
#      - 5558:8000
    expose:
      - 8000
    networks:
      - traefik_proxy
      - esap_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esap-api.entryPoints=esap-api-query"
      - "traefik.http.routers.esap-api.service=esap-api"
      - "traefik.http.routers.esap-api.rule=Host(`sdc.astron.nl`) && PathPrefix(`/esap-api`)"
      - "traefik.http.services.esap-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.esap-qstatic.entryPoints=esap-api-query"
      - "traefik.http.routers.esap-qstatic.service=esap-qstatic"
      - "traefik.http.routers.esap-qstatic.rule=Host(`sdc.astron.nl`) && PathPrefix(`/static`)"
      - "traefik.http.services.esap-qstatic.loadbalancer.server.port=8000"
    env_file:
      - $HOME/shared/oidc
    restart: always
    volumes:
      - $HOME/shared/esap-gateway-query/:/shared

  esap_gui:
    build:
        context: $HOME/my_docker/esap-gui
        dockerfile: Dockerfile
    container_name: esap-gui
    ports:
      - "8017:80"
    expose:
      - "8017"
    networks:
      - esap_network
    restart: always

  esap_nginx:
    build:
        context: $HOME/shared
        dockerfile: Dockerfile
    container_name: esap_nginx
    image: esap_nginx:latest
    networks:
      - traefik_proxy
      - esap_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esap-gui.entryPoints=websecure"
      - "traefik.http.routers.esap-gui.service=esap-gui"
      - "traefik.http.routers.esap-gui.rule=Host(`sdc.astron.nl`) && PathPrefix(`/esap-gui`)"
      - "traefik.http.services.esap-gui.loadbalancer.server.port=80"
      - "traefik.http.routers.esap-static.entryPoints=websecure"
      - "traefik.http.routers.esap-static.service=esap-static"
      - "traefik.http.routers.esap-static.rule=Host(`sdc.astron.nl`) && PathPrefix(`/static`)"
      - "traefik.http.services.esap-static.loadbalancer.server.port=80"
      - "traefik.http.routers.esap-static_esap.entryPoints=websecure"
      - "traefik.http.routers.esap-static_esap.service=esap-static_esap"
      - "traefik.http.routers.esap-static_esap.rule=Host(`sdc.astron.nl`) && PathPrefix(`/static_esap`)"
      - "traefik.http.services.esap-static_esap.loadbalancer.server.port=80"
      - "traefik.http.routers.esap-gui-api.entryPoints=websecure"
      - "traefik.http.routers.esap-gui-api.service=esap-gui-api"
      - "traefik.http.routers.esap-gui-api.rule=Host(`sdc.astron.nl`) && PathPrefix(`/esap-api`)"
      - "traefik.http.services.esap-gui-api.loadbalancer.server.port=80"
      - "traefik.http.routers.esap-oidc.entryPoints=websecure"
      - "traefik.http.routers.esap-oidc.service=esap-oidc"
      - "traefik.http.routers.esap-oidc.rule=Host(`sdc.astron.nl`) && PathPrefix(`/oidc`)"
      - "traefik.http.services.esap-oidc.loadbalancer.server.port=80"
#    ports:
#      - 80:80
    volumes:
      - $HOME/shared:/shared
      - $HOME/shared:/etc/nginx/conf.d
      - $HOME/shared/static:/static
    restart: always

