version: '3.4'

services:
  esap_api:
    image: esap_api:latest
    build:
      context: ${ESAP_ROOT}/esap-api-gateway/esap
      dockerfile: Dockerfile
    container_name: esap_api
    ports:
      - 8000:8000
    environment:
      OIDC_RP_CLIENT_ID: ""
      OIDC_RP_CLIENT_SECRET: ""
      OIDC_OP_JWKS_ENDPOINT: ""
      OIDC_OP_AUTHORIZATION_ENDPOINT: ""
      OIDC_OP_TOKEN_ENDPOINT: ""
      OIDC_OP_USER_ENDPOINT: ""
      LOGIN_REDIRECT_URL: ""
      LOGOUT_REDIRECT_URL: ""
      LOGIN_REDIRECT_URL_FAILURE: ""
      RUCIO_HOST: https://escape-rucio.cern.ch
      RUCIO_AUTH_HOST: https://escape-rucio-auth.cern.ch/
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000 --settings=esap.settings.dev"
    volumes:
        - ${ESAP_ROOT}/esap-api-gateway/esap:/src

  esap_gui:
    environment:
      OIDC_RP_CLIENT_ID: ""
      OIDC_RP_CLIENT_SECRET: ""
      OIDC_OP_JWKS_ENDPOINT: ""
      OIDC_OP_AUTHORIZATION_ENDPOINT: ""
      OIDC_OP_TOKEN_ENDPOINT: ""
      OIDC_OP_USER_ENDPOINT: ""
      LOGIN_REDIRECT_URL: ""
      LOGOUT_REDIRECT_URL: ""
      LOGIN_REDIRECT_URL_FAILURE: ""
      NODE_ENV: "development"
    build:
      context: ${ESAP_ROOT}/esap-gui
      dockerfile: ${ESAP_ROOT}/esap-api-gateway/esap/docker/ska/Dockerfile
    container_name: esap_gui
    image: esap_gui:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - ${ESAP_ROOT}/esap-api-gateway/esap/docker/ska/nginx.conf:/etc/nginx/conf.d/nginx.conf
