ingress:
  enabled: true
  className: ""
  annotations: {}
    #cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: esap-api.combin-ingress.cscs.ch
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #- secretName: esap-api.tls-secret
  #  hosts:
  #  - esap-api.combin-ingress.cscs.ch

