# Generated by Django 3.1.1 on 2020-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esapuserprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='esapuserprofile',
            name='user_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
