# Generated by Django 3.1.4 on 2021-05-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201113_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='esapuserprofile',
            name='sub',
            field=models.CharField(default='sub', max_length=50, null=True, verbose_name='sub'),
        ),
        migrations.AlterField(
            model_name='esapuserprofile',
            name='query_schema',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.esapqueryschema', verbose_name='Preferred Query Schema'),
        ),
    ]
