# Generated by Django 3.1.4 on 2021-05-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210528_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='esapuserprofile',
            name='uid',
            field=models.CharField(default='uid', max_length=255, null=True, verbose_name='uid'),
        ),
    ]
