# Generated by Django 3.1.4 on 2021-06-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_esapuserprofile_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esapuserprofile',
            name='shopping_cart',
        ),
        migrations.AddField(
            model_name='esapshoppingitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='accounts.esapuserprofile', verbose_name='Shopping Cart'),
        ),
    ]
