# Generated by Django 3.1.4 on 2021-06-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210615_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='esapuserprofile',
            name='oidc_id_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='esapshoppingitem',
            name='user_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='accounts.esapuserprofile', verbose_name='User Profile'),
        ),
    ]
