# Generated by Django 3.1.4 on 2021-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210629_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='esapuserprofile',
            name='oidc_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
