# Generated by Django 3.1.4 on 2021-07-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_esapuserprofile_oidc_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='esapuserprofile',
            name='id_token_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
